#!/bin/bash
# This script is part of toshlcd.
# Copyright (C) 2007  Mathieu Larose <mathieu@mathieularose.com>
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
 
lcd=$(cat /proc/toshlcd)
proc_entry="/proc/toshlcd"

case "$1" in
    "inc")
         let "lcd += 1";
         echo $lcd > $proc_entry;
         ;;
    "dec")
         let "lcd -= 1";
         echo $lcd > $proc_entry;
         ;;
    *)
         echo $1 > $proc_entry;
         ;;
esac
